### Pandas

### File I/O

![alt text](read_file.png "Title")

In [2]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("/Users/pluo/Project/AlgomaLecture/COSC5806/Estuary_fish.csv")

df.to_csv("/Users/pluo/Project/AlgomaLecture/COSC5806/Estuary_fish2.tsv", sep='\t', index=False)

In [8]:
df.head()

  Management    Shore  Length
0  Protected  Healthy    10.4
1  Protected  Healthy     2.0
2  Protected  Healthy     3.0
3  Protected  Healthy     7.3
4  Protected  Healthy     9.2

In [ ]:
pd.read_csv('', nrows=5)

In [ ]:
#HDF5, arrow

xlsx = pd.ExcelFile('examples/ex1.xlsx')
pd.read_excel(xlsx, 'Sheet1')

### Series
A Series is a one-dimensional array-like object containing a sequence of values

In [11]:
obj = pd.Series([4, 7, -5, 3])
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

# obj2['a']

In [13]:
obj2['a']

np.int64(-5)

In [14]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)

In [15]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

# pd.isnull(obj4)
# pd.notnull(obj4)

In [17]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

![alt text](NA.png "Title")

In [18]:
# align by index
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

### DataFrame 
dataframe has both a row and column index; it can be thought of as a dict of Series all sharing the same index.

In [19]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
            'year': [2000, 2001, 2002, 2001, 2002, 2003],
            'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df = pd.DataFrame(data)

In [20]:
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [22]:
# df.head()

pd.DataFrame(data, columns=['year', 'state', 'pop']) #column order

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [23]:
# column
df['state']
df.state # only works when the column name is a valid Python variable name

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [27]:
# row
df.index = ['zero',"one",'two','three','four','five']
# df
df.loc['three']

state    Nevada
year       2001
pop         2.4
Name: three, dtype: object

In [30]:
# When you are assigning lists or arrays to a column, the value’s length must match the length of the DataFrame. 
# If you assign a Series, its labels will be realigned exactly to the DataFrame’s index, inserting missing values in any holes:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
  index=['one', 'two', 'three', 'four',
      'five', 'six'])
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val

In [36]:
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [35]:
# new column
frame2['eastern'] = frame2.state == 'Ohio'
# remove column
del frame2['eastern']

In [40]:
# another way to create dataframe
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
df = pd.DataFrame(pop)
df

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [42]:
# As with Series, the values attribute returns the data contained in the DataFrame as a two-dimensional ndarray:
df.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [44]:
df.index = ["1","2","3"]
df.columns = ["one","two"]
df

   one  two
1  2.4  1.7
2  2.9  3.6
3  NaN  1.5

In [45]:
# reindexing
# create a new object with the data conformed to a new index. 
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [46]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame3 = frame.reindex(columns=['Texas', 'Utah', 'California'])

In [48]:
frame3

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [50]:
#drop
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj = obj.drop(['d', 'c'])

obj

# Many functions, like drop, which modify the size or shape of a Series or DataFrame, can manipulate an object in-place without returning a new object

a    0.0
b    1.0
e    4.0
dtype: float64

In [53]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

print(data)
data = data.drop(['Colorado', 'Ohio'])
print(data)
data=  data.drop(['two', 'four'], axis='columns') # axis=1
print(data)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15
          one  three
Utah        8     10
New York   12     14

In [57]:
# Indexing into a DataFrame is for retrieving one or more columns either with a single value or sequence:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

# data[:2]
print(data)
print(data[data['three'] > 5])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
df.loc["Colorado","two"]
df.iloc[1,2]

![alt text](loc.png "Title")
![alt text](loc1.png "Title")

In [ ]:
# broadcasting
frame - series
frame.sub(series3, axis='index')

In [59]:
# applying a function on one-dimensional arrays to each column or row
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
f = lambda x: x.max() - x.min()
frame.apply(f)
# f computes the difference between the maximum and mininum of a Series, 
# is invoked once on each column in frame.

b    1.797063
d    1.537825
e    2.817345
dtype: float64

In [60]:
# Element-wise Python functions
format = lambda x: '%.2f' % x
frame.applymap(format)

/var/folders/8w/4yrh91l544z78rmvprs1p76c0000gp/T/ipykernel_84993/1950983013.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(format)

            b      d      e
Utah    -0.17   0.03  -0.64
Ohio     1.24  -1.42   0.37
Texas   -0.56  -0.14  -0.32
Oregon   0.10   0.12  -2.45

In [61]:
# statistics
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
        [np.nan, np.nan], [0.75, -1.3]],
            index=['a', 'b', 'c', 'd'],
        columns=['one', 'two'])
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

![alt text](stats.png "Title")

### Data clearning and preparation

In [ ]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])


string_data.isnull()

In [ ]:
dropna
fillna
isnull
notnull

In [ ]:
# remove duplicates
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

data.duplicated()
data.drop_duplicates()
data.drop_duplicates(['k1']) # using k1 column to drop dupicates

In [62]:
# Python has long been a popular raw data manipulation language in part due to its ease of use for string and text processing.
val = 'a,b,  guido'
pieces = val.split(',')
'::'.join(pieces)

# val.index(',')

'a::b::  guido'