### Data cleaning and preparation

In [ ]:
from numpy import nan as NA
import pandas as pd
import numpy as np

![alt text](na.png "Title")

In [ ]:
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
print(data)

cleaned = data.dropna() # default for rows

print("\n")
print(cleaned)

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0


     0    1    2
0  1.0  6.5  3.0

In [ ]:
data.dropna(axis=1, how='all') # drop columns with all NA values

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
# Filling In Missing Data
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA

print(df)

print(df.fillna(0))

print(df.fillna({1: 0.5, 2: 0})) # fill column 1 with 0.5 and column 2 with 0

          0         1         2
0  0.046261       NaN       NaN
1 -1.909386       NaN       NaN
2  1.198172       NaN  1.068999
3 -1.270502       NaN -0.152622
4  1.557910  0.564206  2.250686
5  0.219370 -1.246081 -0.001354
6 -0.309289 -1.023866 -0.085057
          0         1         2
0  0.046261  0.000000  0.000000
1 -1.909386  0.000000  0.000000
2  1.198172  0.000000  1.068999
3 -1.270502  0.000000 -0.152622
4  1.557910  0.564206  2.250686
5  0.219370 -1.246081 -0.001354
6 -0.309289 -1.023866 -0.085057
          0         1         2
0  0.046261  0.500000  0.000000
1 -1.909386  0.500000  0.000000
2  1.198172  0.500000  1.068999
3 -1.270502  0.500000 -0.152622
4  1.557910  0.564206  2.250686
5  0.219370 -1.246081 -0.001354
6 -0.309289 -1.023866 -0.085057

In [ ]:
df.ffill()

          0         1         2
0  0.046261       NaN       NaN
1 -1.909386       NaN       NaN
2  1.198172       NaN  1.068999
3 -1.270502       NaN -0.152622
4  1.557910  0.564206  2.250686
5  0.219370 -1.246081 -0.001354
6 -0.309289 -1.023866 -0.085057

In [ ]:
df.bfill()

          0         1         2
0  0.046261  0.564206  1.068999
1 -1.909386  0.564206  1.068999
2  1.198172  0.564206  1.068999
3 -1.270502  0.564206 -0.152622
4  1.557910  0.564206  2.250686
5  0.219370 -1.246081 -0.001354
6 -0.309289 -1.023866 -0.085057

In [ ]:
print(data.fillna(data.mean())) # fill with mean of data

     0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

![alt text](na2.png "Title")

In [ ]:
# duplicates

data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
print(data)

data.duplicated()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
# Transforming Data Using a Function or Mapping

data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                              'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
print(data)
meat_to_animal = {
      'bacon': 'pig',
      'pulled pork': 'pig',
      'pastrami': 'cow',
      'corned beef': 'cow',
      'honey ham': 'pig',
      'nova lox': 'salmon'
}

lowercased = data['food'].str.lower()

data['animal'] = lowercased.map(meat_to_animal)
print(data)

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0
          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [ ]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [ ]:
# filtering out outliers

data = pd.DataFrame(np.random.randn(1000, 4))

data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.010602     0.014423    -0.032169    -0.022130
std       1.014861     1.008130     1.006399     0.948046
min      -2.916793    -3.116913    -3.201883    -3.773563
25%      -0.697910    -0.704132    -0.681474    -0.667619
50%       0.021231     0.032634    -0.003625    -0.018542
75%       0.685615     0.699790     0.644097     0.585438
max       3.884521     3.233678     2.828179     2.851210

In [ ]:
data[np.abs(data) > 3] = np.sign(data) * 3
print(data.describe())

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.009542     0.014306    -0.031921    -0.020592
std       1.011328     1.007053     1.005645     0.942599
min      -2.916793    -3.000000    -3.000000    -3.000000
25%      -0.697910    -0.704132    -0.681474    -0.667619
50%       0.021231     0.032634    -0.003625    -0.018542
75%       0.685615     0.699790     0.644097     0.585438
max       3.000000     3.000000     2.828179     2.851210